Add game page
iurynogueira/angular-clean pull request #45
Opened 2022-06-30 20:46 UTC by iurynogueira

fix #39

2022-07-01 14:10 UTC, MarcosOliveir4 approved these changes

2022-07-01 14:51 UTC, mizek1 requested changes

2022-07-01 14:51 UTC, mizek1 commented on src/app/pages/game/game.component.html
> +  <h2>Tente adivinhar o campeão selecionando um capeão abaixo.</h2>
```suggestion
  <h2>Tente adivinhar o campeão selecionando um campeão abaixo.</h2>
```

2022-07-01 16:27 UTC, iurynogueira commented
> This is the final layout? I think we should use icons instead of text to sinalize the stats and if they're bigger, smaller etc. I also think that the user should be able to type the name of a champion and then select it from the list, not only select from the list.

No. We can improve this result layout now, in select we can open other issue to improve her, what do you think?

2022-07-01 21:24 UTC, mizek1 commented
Hmmmm I just noticed, we forgot to add the champion class comparison, right? (If it's fighter, assassin, etc.)

2022-07-04 14:51 UTC, iurynogueira commented
> Hmmmm I just noticed, we forgot to add the champion class comparison, right? (If it's fighter, assassin, etc.)

Sorry, added and improve layout to correct icons.

<img width="897" alt="image" src="https://user-images.githubusercontent.com/6165180/177178291-c7998c42-4fea-4d47-8357-49a044002c68.png">

2022-07-04 15:17 UTC, mizek1 approved these changes

2022-07-04 16:23 UTC, merged